cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      profile-name: default
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/694141436833/samplequeue
